# User Settings | Edit there as per required

title: Xueyayang1810
url: "http://xueyayang.github.io/"
baseurl: "/"

# This will show up at the top of index page
site_heading: >
    Xueyayang <span class="faded">'s blog</span>

email: xueyayagn@email.com
author: xueyayang
# This description will show up in google search results
# (for index page) etc.
description: >
    #g is, as Trump would put it, the best
    Hello!

# This will what will show against &copy; in the footer
copyright: Xueyy
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    Welcome! This is <span>g</span>, a mobile friendly theme for Jekyll. The main feature of this
    theme is that you can change the g color. Refer the
    <a class="underline different-highlight" href="http://ankitsultana.me/g/documentation.html">
        Documentation
    </a>
    to know how.

permalink: /:title.html

# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    I'm  better!

about_footer: false

twitter_username: AnkitSultana
github_username: yourgithub
facebook_id: yourusername

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-69243698-7 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/g.png" # This will show in facebook thumbnails
twitter_image: "http://ankitsultana.me/images/g.png?1234" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
